# Generated by Django 4.2.2 on 2023-06-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="solved_count",
            field=models.IntegerField(default=0),
        ),
    ]
