# Generated by Django 4.2.2 on 2023-06-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_solved_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="solved_puzzles",
            field=models.TextField(blank=True),
        ),
    ]
